# Uncomment the next line to define a global platform for your project
# platform :ios, '15'

target 'KanyeApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KanyeApi

pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit'

end
